name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04']
        node-version: ['12','16']
        toxenv: ['js_tests', 'js_lint']
    steps:
    - uses: actions/checkout@v1

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set display to virtual frame buffer
      run: export DISPLAY=:99.0

    - name: Run tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
